import type { ResumeData } from "@/types";

export const SAMPLE_RESUMES: Record<string, ResumeData> = {
  "titan": {
    personal: {
      fullName: "James A. Whitmore",
      title: "Chief Operating Officer",
      email: "j.whitmore@example.com",
      phone: "+1 (415) 555-0142",
      location: "San Francisco, CA",
      linkedin: "linkedin.com/in/jameswhitmore",
      github: "",
      portfolio: "",
      website: "",
      photo: "",
    },
    summary:
      "Operations executive with 18+ years scaling technology and logistics organizations. Led a 40% operating margin improvement and a 3x throughput expansion across global teams. Known for building high-performing leadership teams and driving measurable EBITDA growth.",
    skills: [
      { id: "s1", name: "Strategic Planning", level: "", order: 0 },
      { id: "s2", name: "Operations Management", level: "", order: 1 },
      { id: "s3", name: "P&L Ownership", level: "", order: 2 },
      { id: "s4", name: "Team Leadership", level: "", order: 3 },
      { id: "s5", name: "Process Improvement", level: "", order: 4 },
      { id: "s6", name: "Vendor Negotiation", level: "", order: 5 },
      { id: "s7", name: "Change Management", level: "", order: 6 },
    ],
    experience: [
      {
        id: "e1",
        company: "Meridian Global",
        role: "Chief Operating Officer",
        location: "San Francisco, CA",
        startDate: "2021",
        endDate: "Present",
        current: true,
        description: "",
        bullets: [
          "Lead 2,400 employees across 14 regions, delivering 32% revenue growth and a 40% improvement in operating margin in two years.",
          "Spearheaded the enterprise digital transformation program, automating 60% of manual workflows and saving $18M annually.",
          "Restructured global supply chain, cutting lead times by 28% while improving on-time delivery to 99.2%.",
        ],
        order: 0,
      },
      {
        id: "e2",
        company: "Atlas Industries",
        role: "Vice President, Operations",
        location: "Seattle, WA",
        startDate: "2016",
        endDate: "2021",
        current: false,
        description: "",
        bullets: [
          "Scaled operations from 400 to 1,800 employees across three new facilities, increasing throughput by 3x.",
          "Drove a Six Sigma lean program that reduced manufacturing defects by 45%.",
        ],
        order: 1,
      },
    ],
    projects: [],
    certifications: [
      { id: "c1", name: "Certified Executive Leadership", issuer: "Wharton Executive Education", year: "2020", url: "", order: 0 },
      { id: "c2", name: "Six Sigma Black Belt", issuer: "ASQ", year: "2018", url: "", order: 1 },
    ],
    achievements: [
      { id: "a1", title: "Operations Leader of the Year", detail: "Industry Association", year: "2022", order: 0 },
    ],
    internships: [],
    languages: [],
    interests: [{ id: "i1", name: "Executive Mentoring", order: 0 }, { id: "i2", name: "Economic Policy", order: 1 }],
    education: [
      {
        id: "ed1",
        school: "Harvard Business School",
        degree: "MBA",
        field: "General Management",
        startDate: "2008",
        endDate: "2010",
        grade: "Graduated with Distinction",
        description: "",
        order: 0,
      },
    ],
    customSections: [],
  },

  "vector": {
    personal: {
      fullName: "Sara Mitchell",
      title: "Senior Data Analyst",
      email: "sara.mitchell@example.com",
      phone: "+1 (312) 555-0178",
      location: "Chicago, IL",
      linkedin: "linkedin.com/in/saramitchell",
      github: "github.com/saramitchell",
      portfolio: "",
      website: "",
      photo: "",
    },
    summary:
      "Detail-oriented data analyst with 7 years of experience turning raw data into strategic business decisions. Expert in SQL, dashboard design, and A/B testing. Reduced reporting turnaround by 60% through automated pipelines.",
    skills: [
      { id: "s1", name: "SQL", level: "Advanced", order: 0 },
      { id: "s2", name: "Python", level: "Intermediate", order: 1 },
      { id: "s3", name: "Excel", level: "Advanced", order: 2 },
      { id: "s4", name: "Tableau", level: "Advanced", order: 3 },
      { id: "s5", name: "Power BI", level: "Intermediate", order: 4 },
      { id: "s6", name: "Statistics", level: "Advanced", order: 5 },
      { id: "s7", name: "A/B Testing", level: "Intermediate", order: 6 },
      { id: "s8", name: "Data Visualization", level: "Advanced", order: 7 },
    ],
    experience: [
      {
        id: "e1",
        company: "Northwind Analytics",
        role: "Senior Data Analyst",
        location: "Chicago, IL",
        startDate: "2020",
        endDate: "Present",
        current: true,
        description: "",
        bullets: [
          "Built self-service dashboards used by 200+ stakeholders, reducing ad-hoc reporting requests by 60%.",
          "Led A/B testing program that lifted conversion by 18% across the e-commerce funnel.",
          "Automated ETL pipelines with Python and SQL, saving 15 hours of manual work weekly.",
        ],
        order: 0,
      },
      {
        id: "e2",
        company: "Clearview Corporation",
        role: "Data Analyst",
        location: "Madison, WI",
        startDate: "2017",
        endDate: "2020",
        current: false,
        description: "",
        bullets: [
          "Analyzed customer churn drivers and recommended retention plays that reduced churn by 12%.",
          "Maintained a warehouse of 40+ datasets with 99.9% data-quality accuracy.",
        ],
        order: 1,
      },
    ],
    projects: [],
    certifications: [
      { id: "c1", name: "Google Data Analytics Professional", issuer: "Google", year: "2019", url: "", order: 0 },
      { id: "c2", name: "Tableau Desktop Specialist", issuer: "Tableau", year: "2021", url: "", order: 1 },
    ],
    achievements: [],
    internships: [],
    languages: [],
    interests: [],
    education: [
      {
        id: "ed1",
        school: "University of Illinois",
        degree: "B.S.",
        field: "Statistics",
        startDate: "2013",
        endDate: "2017",
        grade: "GPA 3.9 / 4.0",
        description: "",
        order: 0,
      },
    ],
    customSections: [],
  },

  "aurora": {
    personal: {
      fullName: "Daniel Chen",
      title: "Senior Software Engineer",
      email: "daniel.chen@example.com",
      phone: "+1 (206) 555-0166",
      location: "Seattle, WA",
      linkedin: "linkedin.com/in/danielchen",
      github: "github.com/danielchen",
      portfolio: "danielchen.dev",
      website: "",
      photo: "",
    },
    summary:
      "Full-stack engineer with 8 years building scalable web platforms serving 10M+ users. Deep expertise in TypeScript, distributed systems, and cloud infrastructure. Led migrations that cut infrastructure costs by 35%.",
    skills: [
      { id: "s1", name: "TypeScript", level: "", order: 0 },
      { id: "s2", name: "React", level: "", order: 1 },
      { id: "s3", name: "Node.js", level: "", order: 2 },
      { id: "s4", name: "Go", level: "", order: 3 },
      { id: "s5", name: "PostgreSQL", level: "", order: 4 },
      { id: "s6", name: "AWS", level: "", order: 5 },
      { id: "s7", name: "Docker", level: "", order: 6 },
      { id: "s8", name: "GraphQL", level: "", order: 7 },
    ],
    experience: [
      {
        id: "e1",
        company: "Vertex Systems",
        role: "Senior Software Engineer",
        location: "Seattle, WA",
        startDate: "2021",
        endDate: "Present",
        current: true,
        description: "",
        bullets: [
          "Led the rewrite of the core API in Go, reducing p99 latency from 900ms to 140ms at 40k RPS.",
          "Architected a multi-region deployment that improved availability to 99.99%.",
          "Mentored a team of 6 engineers; 3 promoted within a year.",
        ],
        order: 0,
      },
      {
        id: "e2",
        company: "CloudNine",
        role: "Software Engineer",
        location: "Portland, OR",
        startDate: "2017",
        endDate: "2021",
        current: false,
        description: "",
        bullets: [
          "Shipped the analytics dashboard used by 500+ enterprise customers.",
          "Introduced CI/CD pipelines that cut release cycles from weeks to daily.",
        ],
        order: 1,
      },
    ],
    projects: [
      {
        id: "p1",
        name: "OpenAuth",
        link: "github.com/danielchen/openauth",
        tech: "TypeScript · OAuth2 · Redis",
        startDate: "2022",
        endDate: "Present",
        description: "",
        bullets: ["Open-source OAuth2 provider library with 12k GitHub stars and 30+ contributors."],
        order: 0,
      },
    ],
    certifications: [
      { id: "c1", name: "AWS Solutions Architect", issuer: "Amazon", year: "2022", url: "", order: 0 },
      { id: "c2", name: "CKAD: Certified Kubernetes", issuer: "CNCF", year: "2021", url: "", order: 1 },
    ],
    achievements: [],
    internships: [],
    languages: [{ id: "l1", name: "English", level: "Native", order: 0 }, { id: "l2", name: "Mandarin", level: "Fluent", order: 1 }],
    interests: [{ id: "i1", name: "Open Source", order: 0 }, { id: "i2", name: "Hiking", order: 1 }],
    education: [
      {
        id: "ed1",
        school: "University of Washington",
        degree: "B.S.",
        field: "Computer Science",
        startDate: "2013",
        endDate: "2017",
        grade: "Magna Cum Laude",
        description: "",
        order: 0,
      },
    ],
    customSections: [],
  },

  "nexus": {
    personal: {
      fullName: "Priya Sharma",
      title: "Product Designer",
      email: "priya.sharma@example.com",
      phone: "+1 (415) 555-0133",
      location: "Austin, TX",
      linkedin: "linkedin.com/in/priyasharma",
      github: "",
      portfolio: "priyasharma.design",
      website: "",
      photo: "",
    },
    summary:
      "Product designer with 6 years crafting intuitive digital experiences for fintech and SaaS products. Shipped 20+ products end-to-end and grew NPS by 25 points through research-driven design systems.",
    skills: [
      { id: "s1", name: "Figma", level: "", order: 0 },
      { id: "s2", name: "Design Systems", level: "", order: 1 },
      { id: "s3", name: "Prototyping", level: "", order: 2 },
      { id: "s4", name: "User Research", level: "", order: 3 },
      { id: "s5", name: "Interaction Design", level: "", order: 4 },
      { id: "s6", name: "HTML & CSS", level: "", order: 5 },
      { id: "s7", name: "Motion Design", level: "", order: 6 },
    ],
    experience: [
      {
        id: "e1",
        company: "Pixelworks",
        role: "Senior Product Designer",
        location: "Austin, TX",
        startDate: "2021",
        endDate: "Present",
        current: true,
        description: "",
        bullets: [
          "Owned the end-to-end redesign of the onboarding flow, increasing activation by 32%.",
          "Built and maintained a tokenized design system used across 12 product teams.",
          "Conducted 40+ user interviews and usability studies to inform product strategy.",
        ],
        order: 0,
      },
      {
        id: "e2",
        company: "Lumen Studio",
        role: "Product Designer",
        location: "Remote",
        startDate: "2018",
        endDate: "2021",
        current: false,
        description: "",
        bullets: [
          "Designed award-winning mobile app experiences for 3 clients in the health-tech space.",
          "Shipped a reusable component library that halved design-to-dev handoff time.",
        ],
        order: 1,
      },
    ],
    projects: [
      {
        id: "p1",
        name: "Reimburse — Finance App",
        link: "",
        tech: "Figma · Prototyping",
        startDate: "2023",
        endDate: "2024",
        description: "",
        bullets: ["Full redesign of an expense-tracking app; trial-to-paid conversion rose 21%."],
        order: 0,
      },
    ],
    certifications: [
      { id: "c1", name: "UX Research & Strategy", issuer: "NN/g", year: "2022", url: "", order: 0 },
      { id: "c2", name: "Google UX Design Certificate", issuer: "Google", year: "2020", url: "", order: 1 },
    ],
    achievements: [],
    internships: [],
    languages: [],
    interests: [{ id: "i1", name: "Photography", order: 0 }, { id: "i2", name: "UI Illustration", order: 1 }],
    education: [
      {
        id: "ed1",
        school: "Savannah College of Art & Design",
        degree: "B.F.A.",
        field: "Interaction Design",
        startDate: "2014",
        endDate: "2018",
        grade: "Summa Cum Laude",
        description: "",
        order: 0,
      },
    ],
    customSections: [],
  },

  "apex": {
    personal: {
      fullName: "Eleanor Vane",
      title: "Finance Director",
      email: "e.vane@example.com",
      phone: "+1 (212) 555-0127",
      location: "New York, NY",
      linkedin: "linkedin.com/in/eleanorvane",
      github: "",
      portfolio: "",
      website: "",
      photo: "",
    },
    summary:
      "Finance executive with 14 years in corporate strategy and FP&A. Drove M&A diligence on $2B+ in transactions and led a finance transformation that cut close cycles by 40%. Chartered accountant with deep P&L experience.",
    skills: [
      { id: "s1", name: "Financial Modeling", level: "", order: 0 },
      { id: "s2", name: "FP&A", level: "", order: 1 },
      { id: "s3", name: "Budgeting", level: "", order: 2 },
      { id: "s4", name: "Corporate Strategy", level: "", order: 3 },
      { id: "s5", name: "Mergers & Acquisitions", level: "", order: 4 },
      { id: "s6", name: "Risk Management", level: "", order: 5 },
    ],
    experience: [
      {
        id: "e1",
        company: "Sterling & Co.",
        role: "Finance Director",
        location: "New York, NY",
        startDate: "2019",
        endDate: "Present",
        current: true,
        description: "",
        bullets: [
          "Lead a team of 12 across FP&A and corporate reporting for a $900M revenue business.",
          "Partnered on 5 acquisitions totaling $640M, delivering $22M in annual synergies.",
          "Transformed the planning cycle, reducing close time from 12 days to 7.",
        ],
        order: 0,
      },
      {
        id: "e2",
        company: "Beacon Capital",
        role: "Senior Financial Analyst",
        location: "Boston, MA",
        startDate: "2015",
        endDate: "2019",
        current: false,
        description: "",
        bullets: [
          "Built the quarterly investor reporting package used by the board and 40+ LPs.",
          "Modeled capital allocation scenarios that increased portfolio IRR by 2.4 points.",
        ],
        order: 1,
      },
    ],
    projects: [],
    certifications: [
      { id: "c1", name: "Certified Public Accountant", issuer: "AICPA", year: "2015", url: "", order: 0 },
      { id: "c2", name: "CFA Level III Candidate", issuer: "CFA Institute", year: "2018", url: "", order: 1 },
    ],
    achievements: [],
    internships: [],
    languages: [],
    interests: [{ id: "i1", name: "Board Governance", order: 0 }, { id: "i2", name: "Financial Literacy Education", order: 1 }],
    education: [
      {
        id: "ed1",
        school: "London School of Economics",
        degree: "M.Sc.",
        field: "Finance",
        startDate: "2011",
        endDate: "2012",
        grade: "Merit",
        description: "",
        order: 0,
      },
    ],
    customSections: [],
  },

  "circuit": {
    personal: {
      fullName: "Marcus Lee",
      title: "Full-Stack Developer",
      email: "marcus.lee@example.com",
      phone: "+1 (303) 555-0191",
      location: "Denver, CO",
      linkedin: "linkedin.com/in/marcuslee",
      github: "github.com/marcuslee",
      portfolio: "",
      website: "",
      photo: "",
    },
    summary:
      "Full-stack developer who loves building fast, modern web applications. 6 years of experience shipping production apps with React and Node.js. Passionate about developer tooling, performance, and clean code.",
    skills: [
      { id: "s1", name: "JavaScript", level: "", order: 0 },
      { id: "s2", name: "React", level: "", order: 1 },
      { id: "s3", name: "Node.js", level: "", order: 2 },
      { id: "s4", name: "PostgreSQL", level: "", order: 3 },
      { id: "s5", name: "Redis", level: "", order: 4 },
      { id: "s6", name: "Docker", level: "", order: 5 },
      { id: "s7", name: "GraphQL", level: "", order: 6 },
    ],
    experience: [
      {
        id: "e1",
        company: "CodeForge Labs",
        role: "Full-Stack Developer",
        location: "Denver, CO",
        startDate: "2021",
        endDate: "Present",
        current: true,
        description: "",
        bullets: [
          "Built a realtime collaboration suite used by 80k teams, handling 1M+ concurrent connections.",
          "Cut initial load time by 55% through code-splitting and aggressive caching.",
          "Introduced typed GraphQL schema generation, eliminating a whole class of runtime errors.",
        ],
        order: 0,
      },
      {
        id: "e2",
        company: "Brightside",
        role: "Frontend Developer",
        location: "Remote",
        startDate: "2018",
        endDate: "2021",
        current: false,
        description: "",
        bullets: [
          "Delivered a design system that unified 4 legacy apps into one consistent interface.",
          "Championed web accessibility; raised Lighthouse accessibility scores to 98+.",
        ],
        order: 1,
      },
    ],
    projects: [
      {
        id: "p1",
        name: "DevMetrics",
        link: "github.com/marcuslee/devmetrics",
        tech: "React · TypeScript · WebSockets",
        startDate: "2022",
        endDate: "Present",
        description: "",
        bullets: ["Self-hosted development analytics dashboard with realtime team metrics."],
        order: 0,
      },
    ],
    certifications: [
      { id: "c1", name: "Meta Front-End Developer", issuer: "Meta", year: "2023", url: "", order: 0 },
      { id: "c2", name: "MongoDB Associate Developer", issuer: "MongoDB", year: "2022", url: "", order: 1 },
    ],
    achievements: [],
    internships: [],
    languages: [],
    interests: [{ id: "i1", name: "Game Jams", order: 0 }, { id: "i2", name: "Coffee Roasting", order: 1 }],
    education: [
      {
        id: "ed1",
        school: "Arizona State University",
        degree: "B.S.",
        field: "Software Engineering",
        startDate: "2014",
        endDate: "2018",
        grade: "GPA 3.8 / 4.0",
        description: "",
        order: 0,
      },
    ],
    customSections: [],
  },

  "scholar": {
    personal: {
      fullName: "Dr. Elena Petrova",
      title: "Research Scientist",
      email: "e.petrova@example.com",
      phone: "+1 (617) 555-0154",
      location: "Cambridge, MA",
      linkedin: "linkedin.com/in/elenapetrova",
      github: "github.com/elenapetrova",
      portfolio: "",
      website: "",
      photo: "",
    },
    summary:
      "Computational physicist with 20 peer-reviewed publications and 4,000+ citations. Six years applying quantitative methods to materials science. Experienced in leading interdisciplinary teams and securing competitive research funding.",
    skills: [
      { id: "s1", name: "Statistical Modeling", level: "", order: 0 },
      { id: "s2", name: "Python", level: "", order: 1 },
      { id: "s3", name: "MATLAB", level: "", order: 2 },
      { id: "s4", name: "Scientific Writing", level: "", order: 3 },
      { id: "s5", name: "Data Analysis", level: "", order: 4 },
      { id: "s6", name: "Simulation", level: "", order: 5 },
    ],
    experience: [
      {
        id: "e1",
        company: "Institute for Advanced Materials",
        role: "Research Scientist",
        location: "Cambridge, MA",
        startDate: "2020",
        endDate: "Present",
        current: true,
        description: "",
        bullets: [
          "Lead a 5-person group studying quantum materials; 3 papers published in top journals.",
          "Awarded $1.2M in NSF funding for high-throughput computational screening research.",
        ],
        order: 0,
      },
      {
        id: "e2",
        company: "University of Vienna",
        role: "Postdoctoral Fellow",
        location: "Vienna, Austria",
        startDate: "2016",
        endDate: "2020",
        current: false,
        description: "",
        bullets: [
          "Developed novel simulation methods now cited by 15 research groups worldwide.",
          "Taught graduate seminars in computational methods for two academic years.",
        ],
        order: 1,
      },
    ],
    projects: [],
    certifications: [
      { id: "c1", name: "Certified Peer Reviewer", issuer: "Elsevier", year: "2019", url: "", order: 0 },
    ],
    achievements: [
      { id: "a1", title: "Early-Career Researcher Award", detail: "Materials Research Society", year: "2021", order: 0 },
    ],
    internships: [],
    languages: [{ id: "l1", name: "English", level: "Fluent", order: 0 }, { id: "l2", name: "Russian", level: "Native", order: 1 }],
    interests: [{ id: "i1", name: "Science Outreach", order: 0 }, { id: "i2", name: "Violin", order: 1 }],
    education: [
      {
        id: "ed1",
        school: "ETH Zürich",
        degree: "Ph.D.",
        field: "Physics",
        startDate: "2012",
        endDate: "2016",
        grade: "Summa Cum Laude",
        description: "",
        order: 0,
      },
    ],
    customSections: [],
  },

  "orbit": {
    personal: {
      fullName: "Arjun Mehta",
      title: "Machine Learning Engineer",
      email: "arjun.mehta@example.com",
      phone: "+1 (650) 555-0118",
      location: "Palo Alto, CA",
      linkedin: "linkedin.com/in/arjunmehta",
      github: "github.com/arjunmehta",
      portfolio: "",
      website: "",
      photo: "",
    },
    summary:
      "Machine learning engineer with 5 years shipping production AI systems. Specialized in NLP and recommendation engines serving 15M monthly users. Deployed models with 99.5% uptime and cut inference latency by 60%.",
    skills: [
      { id: "s1", name: "Python", level: "Advanced", order: 0 },
      { id: "s2", name: "PyTorch", level: "Advanced", order: 1 },
      { id: "s3", name: "TensorFlow", level: "Intermediate", order: 2 },
      { id: "s4", name: "NLP", level: "Advanced", order: 3 },
      { id: "s5", name: "Computer Vision", level: "Intermediate", order: 4 },
      { id: "s6", name: "MLOps", level: "Advanced", order: 5 },
      { id: "s7", name: "SQL", level: "Advanced", order: 6 },
    ],
    experience: [
      {
        id: "e1",
        company: "Deepgrid",
        role: "Machine Learning Engineer",
        location: "Palo Alto, CA",
        startDate: "2021",
        endDate: "Present",
        current: true,
        description: "",
        bullets: [
          "Built the retrieval pipeline powering a search assistant, improving relevance by 27%.",
          "Reduced model inference cost by 45% via quantization and model distillation.",
          "Owned the ML training platform used by 9 teams across the company.",
        ],
        order: 0,
      },
      {
        id: "e2",
        company: "Quantia Labs",
        role: "Data Scientist",
        location: "Remote",
        startDate: "2019",
        endDate: "2021",
        current: false,
        description: "",
        bullets: [
          "Developed a churn-prediction model that saved $3.4M annually in customer retention.",
          "Built automated feature pipelines that reduced experiment turnaround from weeks to days.",
        ],
        order: 1,
      },
    ],
    projects: [
      {
        id: "p1",
        name: "RAG Search Engine",
        link: "github.com/arjunmehta/ragsearch",
        tech: "PyTorch · FastAPI · Vector DB",
        startDate: "2023",
        endDate: "Present",
        description: "",
        bullets: ["Retrieval-augmented generation system with sub-200ms answer latency."],
        order: 0,
      },
    ],
    certifications: [
      { id: "c1", name: "Azure AI Engineer Associate", issuer: "Microsoft", year: "2022", url: "", order: 0 },
      { id: "c2", name: "TensorFlow Developer", issuer: "Google", year: "2021", url: "", order: 1 },
    ],
    achievements: [],
    internships: [],
    languages: [],
    interests: [{ id: "i1", name: "Kaggle Competitions", order: 0 }, { id: "i2", name: "Chess", order: 1 }],
    education: [
      {
        id: "ed1",
        school: "Carnegie Mellon University",
        degree: "M.S.",
        field: "Machine Learning",
        startDate: "2017",
        endDate: "2019",
        grade: "GPA 4.0 / 4.0",
        description: "",
        order: 0,
      },
    ],
    customSections: [],
  },

  "launch": {
    personal: {
      fullName: "Lily Nguyen",
      title: "Marketing Graduate",
      email: "lily.nguyen@example.com",
      phone: "+1 (213) 555-0121",
      location: "Los Angeles, CA",
      linkedin: "linkedin.com/in/lilynguyen",
      github: "",
      portfolio: "",
      website: "",
      photo: "",
    },
    summary:
      "Recent marketing graduate with hands-on internship experience in content strategy and social media. Grew a university brand's Instagram by 300% in one semester. Eager to bring creativity and data-driven thinking to a growth team.",
    skills: [
      { id: "s1", name: "Content Marketing", level: "", order: 0 },
      { id: "s2", name: "Social Media", level: "", order: 1 },
      { id: "s3", name: "SEO", level: "", order: 2 },
      { id: "s4", name: "Google Analytics", level: "", order: 3 },
      { id: "s5", name: "Copywriting", level: "", order: 4 },
      { id: "s6", name: "Canva", level: "", order: 5 },
    ],
    experience: [
      {
        id: "e1",
        company: "Campus Marketing Team",
        role: "Marketing Assistant",
        location: "Los Angeles, CA",
        startDate: "2023",
        endDate: "Present",
        current: true,
        description: "",
        bullets: [
          "Planned and executed 12 campus events with average attendance of 400+ students.",
          "Produced weekly email newsletters with a 34% open rate.",
        ],
        order: 0,
      },
    ],
    projects: [],
    certifications: [
      { id: "c1", name: "Google Ads Search Certification", issuer: "Google", year: "2024", url: "", order: 0 },
      { id: "c2", name: "HubSpot Inbound Marketing", issuer: "HubSpot", year: "2023", url: "", order: 1 },
    ],
    achievements: [
      { id: "a1", title: "Dean's List", detail: "All four years", year: "2020-2024", order: 0 },
    ],
    internships: [
      {
        id: "in1",
        company: "Bright Marketing Agency",
        role: "Marketing Intern",
        startDate: "2024",
        endDate: "Present",
        current: true,
        description: "",
        bullets: ["Managed client social calendars and grew engagement by 45% across 3 accounts."],
        order: 0,
      },
    ],
    languages: [],
    interests: [{ id: "i1", name: "Content Creation", order: 0 }, { id: "i2", name: "Rock Climbing", order: 1 }],
    education: [
      {
        id: "ed1",
        school: "University of Southern California",
        degree: "B.A.",
        field: "Marketing",
        startDate: "2020",
        endDate: "2024",
        grade: "GPA 3.7 / 4.0",
        description: "",
        order: 0,
      },
    ],
    customSections: [],
  },

  pulse: {
    personal: {
      fullName: "Robert Grant",
      title: "Chief Executive Officer",
      email: "r.grant@example.com",
      phone: "+1 (646) 555-0173",
      location: "New York, NY",
      linkedin: "linkedin.com/in/robertgrant",
      github: "",
      portfolio: "",
      website: "",
      photo: "",
    },
    summary:
      "Chief executive with 20 years leading growth-stage and public companies to market leadership. Guided two organizations to successful exits totaling $1.8B. Builder of aligned, accountable teams and durable competitive advantage.",
    skills: [
      { id: "s1", name: "Corporate Strategy", level: "", order: 0 },
      { id: "s2", name: "Mergers & Acquisitions", level: "", order: 1 },
      { id: "s3", name: "Board Relations", level: "", order: 2 },
      { id: "s4", name: "Turnaround Leadership", level: "", order: 3 },
      { id: "s5", name: "Revenue Growth", level: "", order: 4 },
      { id: "s6", name: "Organizational Design", level: "", order: 5 },
    ],
    experience: [
      {
        id: "e1",
        company: "NorthPeak Holdings",
        role: "Chief Executive Officer",
        location: "New York, NY",
        startDate: "2018",
        endDate: "Present",
        current: true,
        description: "",
        bullets: [
          "Grew revenue from $120M to $410M in five years while expanding operating margin by 9 points.",
          "Executed 4 acquisitions and 2 divestitures that reshaped the company's portfolio.",
          "Built a leadership bench with 40% of senior roles filled from internal promotions.",
        ],
        order: 0,
      },
      {
        id: "e2",
        company: "Vanguard Solutions",
        role: "President",
        location: "Chicago, IL",
        startDate: "2012",
        endDate: "2018",
        current: false,
        description: "",
        bullets: [
          "Led the turnaround of a loss-making division, restoring profitability within 18 months.",
          "Closed a $220M sale of the division, delivering a 3.2x return to shareholders.",
        ],
        order: 1,
      },
    ],
    projects: [],
    certifications: [],
    achievements: [
      { id: "a1", title: "CEO of the Year", detail: "Regional Business Journal", year: "2022", order: 0 },
    ],
    internships: [],
    languages: [],
    interests: [{ id: "i1", name: "Executive Coaching", order: 0 }, { id: "i2", name: "Sailing", order: 1 }],
    education: [
      {
        id: "ed1",
        school: "Northwestern University",
        degree: "MBA",
        field: "Strategy & Finance",
        startDate: "2004",
        endDate: "2006",
        grade: "Graduated with Honors",
        description: "",
        order: 0,
      },
    ],
    customSections: [],
  },
};

export function getSampleResume(slug: string): ResumeData {
  return (
    SAMPLE_RESUMES[slug] ?? {
      personal: {
        fullName: "Your Name",
        title: "Professional Title",
        email: "you@email.com",
        phone: "+1 234 567 8900",
        location: "City, Country",
        linkedin: "linkedin.com/in/you",
        github: "github.com/you",
        portfolio: "",
        website: "",
        photo: "",
      },
      summary: "A compelling professional summary will appear here. Use the AI assistant or write one yourself.",
      education: [
        { id: "e1", school: "University Name", degree: "B.Tech", field: "Computer Science", startDate: "2020", endDate: "2024", grade: "", description: "", order: 0 },
      ],
      experience: [
        { id: "x1", company: "Company Name", role: "Software Engineer", location: "", startDate: "2024", endDate: "Present", current: true, description: "", bullets: ["Achievement-oriented bullet point with measurable impact."], order: 0 },
      ],
      projects: [],
      skills: [
        { id: "s1", name: "JavaScript", level: "", order: 0 },
        { id: "s2", name: "React", level: "", order: 1 },
        { id: "s3", name: "Node.js", level: "", order: 2 },
        { id: "s4", name: "Python", level: "", order: 3 },
      ],
      certifications: [],
      achievements: [],
      internships: [],
      languages: [],
      interests: [],
      customSections: [],
    }
  );
}
