import type { TemplateConfig } from "@/types";

export const TEMPLATES: TemplateConfig[] = [
  {
    slug: "aurora",
    name: "Aurora",
    category: "Engineering",
    description: "A modern engineering layout with a colored sidebar and crisp accent bars — built to make technical skills impossible to miss.",
    atsScore: 90,
    accent: "#2563eb",
    secondary: "#eff6ff",
    textColor: "#0f172a",
    font: "sans",
    layout: "sidebar",
    headerStyle: "sidebar",
    sectionStyle: "bar",
    showPhoto: true,
    monochrome: false,
    signature: "solid",
  },
  {
    slug: "vector",
    name: "Vector",
    category: "ATS-Optimized",
    description: "Fully monochrome, single-column, machine-readable layout with the highest ATS compatibility.",
    atsScore: 99,
    accent: "#111827",
    secondary: "#f3f4f6",
    textColor: "#111827",
    font: "sans",
    layout: "classic",
    headerStyle: "left",
    sectionStyle: "underline",
    showPhoto: false,
    monochrome: true,
    signature: "solid",
  },
  {
    slug: "nexus",
    name: "Nexus",
    category: "Modern",
    description: "A sleek dark header with gradient accents and badge-style sections — a modern look for technology roles.",
    atsScore: 88,
    accent: "#0ea5e9",
    accentDark: "#0369a1",
    secondary: "#e0f2fe",
    textColor: "#0f172a",
    font: "sans",
    layout: "classic",
    headerStyle: "banner",
    sectionStyle: "badge",
    showPhoto: true,
    monochrome: false,
    signature: "gradient",
  },
  {
    slug: "titan",
    name: "Titan",
    category: "Corporate",
    description: "A commanding deep-blue banner with a centered header — built for leadership and senior roles.",
    atsScore: 92,
    accent: "#1d4ed8",
    accentDark: "#1e40af",
    secondary: "#dbeafe",
    textColor: "#1c2333",
    font: "sans",
    layout: "classic",
    headerStyle: "banner",
    sectionStyle: "line",
    showPhoto: true,
    monochrome: false,
    signature: "solid",
  },
  {
    slug: "pulse",
    name: "Pulse",
    category: "Modern Startup",
    description: "A bold, centered layout with strong section rules and energetic framing — made for startup and product-minded people.",
    atsScore: 87,
    accent: "#0f172a",
    secondary: "#334155",
    textColor: "#0f172a",
    font: "serif",
    layout: "classic",
    headerStyle: "centered",
    sectionStyle: "line",
    showPhoto: false,
    monochrome: true,
    signature: "outline",
  },
  {
    slug: "circuit",
    name: "Circuit",
    category: "Developer",
    description: "A striking dark header with cyan glows — a modern look for developers and designers.",
    atsScore: 86,
    accent: "#06b6d4",
    accentDark: "#0e7490",
    secondary: "#083344",
    textColor: "#0f172a",
    font: "sans",
    layout: "classic",
    headerStyle: "banner",
    sectionStyle: "badge",
    showPhoto: true,
    monochrome: false,
    signature: "gradient",
  },
  {
    slug: "scholar",
    name: "Scholar",
    category: "Academic",
    description: "Serif typography and a conservative structure tailored for research, academia, and publications.",
    atsScore: 93,
    accent: "#3f4a5a",
    secondary: "#eef1f5",
    textColor: "#232a36",
    font: "serif",
    layout: "classic",
    headerStyle: "left",
    sectionStyle: "underline",
    showPhoto: false,
    monochrome: true,
    signature: "solid",
  },
  {
    slug: "orbit",
    name: "Orbit",
    category: "Data Science",
    description: "Indigo accents with skill bars and a metrics-forward layout for AI, ML, and data roles.",
    atsScore: 91,
    accent: "#7c3aed",
    accentDark: "#5b21b6",
    secondary: "#ede9fe",
    textColor: "#171226",
    font: "sans",
    layout: "split",
    headerStyle: "left",
    sectionStyle: "bar",
    showPhoto: true,
    monochrome: false,
    signature: "gradient",
  },
  {
    slug: "launch",
    name: "Launch",
    category: "Entry Level",
    description: "A friendly, light layout with rounded badges — ideal for students and internship seekers.",
    atsScore: 94,
    accent: "#0284c7",
    secondary: "#e0f2fe",
    textColor: "#0c2233",
    font: "sans",
    layout: "classic",
    headerStyle: "centered",
    sectionStyle: "badge",
    showPhoto: true,
    monochrome: false,
    signature: "solid",
  },
  {
    slug: "apex",
    name: "Apex",
    category: "Leadership",
    description: "A polished split layout with navy paneling and refined typography for corporate executives.",
    atsScore: 89,
    accent: "#1e3a8a",
    secondary: "#1e293b",
    textColor: "#0f172a",
    font: "serif",
    layout: "split",
    headerStyle: "left",
    sectionStyle: "line",
    showPhoto: true,
    monochrome: false,
    signature: "outline",
  },
];

export function getTemplate(slug: string): TemplateConfig {
  return TEMPLATES.find((t) => t.slug === slug) ?? TEMPLATES[0];
}

export const TEMPLATE_MAP: Record<string, TemplateConfig> = Object.fromEntries(
  TEMPLATES.map((t) => [t.slug, t])
);

export const FONT_STACKS: Record<string, string> = {
  sans: "Inter, 'Plus Jakarta Sans', system-ui, sans-serif",
  serif: "'Georgia', 'Times New Roman', serif",
  mono: "'JetBrains Mono', 'Fira Code', monospace",
};
